### PR TITLE
TW-921: Text to NFT step 1

### PR DESCRIPTION
**Pull request by svjatoslavtt**

### CODE REVIEW

**Review by herkoss — APPROVED** [review]
GJ!

**Review by Boltman92 — APPROVED** [review]

**Review by herkoss — APPROVED** [review]
GJ!

**Review by Boltman92 — APPROVED** [review]

**Review by IrynaKhyzhynska — APPROVED** [review]
android done 1.15_942

**Review by vladvn1905 — APPROVED** [review]
ios done build 1.15_942

**Pull request merged**
