### PR TITLE
TW-689: Add adult overlay to collectibles

### PR DESCRIPTION
**Pull request by svjatoslavtt**

### CODE REVIEW

**Review by herkoss — APPROVED** [review]
Great!

**Review by Boltman92 — APPROVED** [review]

**Review by herkoss — APPROVED** [review]
GJ!

**Review by Boltman92 — APPROVED** [review]

**Review by vladvn1905 — APPROVED** [review]
ios done build: 1.15_713

**Review by IrynaKhyzhynska — APPROVED** [review]
android done build 1.15_713

**Pull request merged**
